# -*- coding: utf-8 -*-
"""E-waste Survey Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10NzFlZd52MIrYv7VtDvYUhBF6qhBECin
"""

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Awareness and Behaviour Related to E-Waste.csv')
print("Dataset loaded successfully. Displaying the first 5 rows:")
df.head()

print("Data types and non-null counts:")
df.info()

print("\nMissing values per column:")
print(df.isnull().sum())

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Awareness and Behaviour Related to E-Waste.csv')

print("Reviewing unique values and value counts for 'object' type columns:\n")

for column in df.columns:
    if df[column].dtype == 'object':
        print(f"Column Name: {column}")
        print("Unique Values:")
        print(df[column].unique())
        print("\nValue Counts:")
        print(df[column].value_counts())
        print("\n" + "-"*50 + "\n")

"""## Formulate Hypotheses

### Subtask:
Based on the examination of the categorical data, formulate specific null and alternative hypotheses that can be tested using Chi-square tests (for relationships between categorical variables) and potentially T-tests (if suitable numerical or ordinal data can be derived).

### Formulated Hypotheses

Based on the review of the 'object' type columns, the following hypotheses are formulated for statistical testing:

#### Chi-square Tests (Categorical vs. Categorical)

These hypotheses test for associations between pairs of categorical variables.

1.  **Awareness of E-waste Term vs. Disposal Behavior:**
    *   **Null Hypothesis (H0):** There is no association between whether a person has heard the term “E-waste” and what they did with their last electronic device.
    *   **Alternative Hypothesis (H1):** There is an association between whether a person has heard the term “E-waste” and what they did with their last electronic device.
    *   *Columns:* `'Have you heard the term “E-waste” before?'` and `'What did you do with the last electronic device you stopped using?'`

2.  **Awareness of E-waste Term vs. Knowledge of Disposal Services:**
    *   **Null Hypothesis (H0):** There is no association between whether a person has heard the term “E-waste” and whether they know of any place or service for safe e-waste disposal.
    *   **Alternative Hypothesis (H1):** There is an association between whether a person has heard the term “E-waste” and whether they know of any place or service for safe e-waste disposal.
    *   *Columns:* `'Have you heard the term “E-waste” before?'` and `'Do you know of any place or service where you can safely dispose of e-waste?'`

3.  **Presence of E-waste at Home vs. Knowledge of Disposal Services:**
    *   **Null Hypothesis (H0):** There is no association between currently having unused or broken electronic items at home and knowing of any place or service for safe e-waste disposal.
    *   **Alternative Hypothesis (H1):** There is an association between currently having unused or broken electronic items at home and knowing of any place or service for safe e-waste disposal.
    *   *Columns:* `'Do you currently have unused or broken electronic items at home?'` and `'Do you know of any place or service where you can safely dispose of e-waste?'`

4.  **Disposal Reason vs. Perception of E-waste Fate:**
    *   **Null Hypothesis (H0):** There is no association between the reason a person chose a particular disposal option for their last device and their perception of what happens to e-waste after it is collected.
    *   **Alternative Hypothesis (H1):** There is an association between the reason a person chose a particular disposal option for their last device and their perception of what happens to e-waste after it is collected.
    *   *Columns:* `'Why did you choose that option?\n(Choose ONE most important reason)'` and `'What do you think happens to e-waste after it is collected?'`

5.  **Interaction with Awareness Company vs. E-waste Term Awareness:**
    *   **Null Hypothesis (H0):** There is no association between having seen or interacted with an awareness company related to e-waste and having heard the term “E-waste” before.
    *   **Alternative Hypothesis (H1):** There is an association between having seen or interacted with an awareness company related to e-waste and having heard the term “E-waste” before.
    *   *Columns:* `'Have you ever seen or interacted with an awareness company related to e-waste?'` and `'Have you heard the term “E-waste” before?'`

#### T-tests (Binary Categorical vs. Ordinal/Numerical)

These hypotheses will be tested if an 'object' type column can be meaningfully converted into an ordinal scale.

1.  **E-waste Term Awareness vs. Quantity of E-waste at Home:**
    *   The column `'Do you currently have unused or broken electronic items at home?'` (values: 'No', 'Yes, 1-2 items', 'Yes, many') can be treated as an ordinal variable.
    *   **Null Hypothesis (H0):** There is no significant difference in the average quantity of unused or broken electronic items at home between those who have heard the term “E-waste” and those who have not.
    *   **Alternative Hypothesis (H1):** There is a significant difference in the average quantity of unused or broken electronic items at home between those who have heard the term “E-waste” and those who have not.
    *   *Variables:* Independent: `'Have you heard the term “E-waste” before?'` (binary: Yes/No). Dependent: Ordinal conversion of `'Do you currently have unused or broken electronic items at home?'`.

#### Hypotheses for Multi-select Columns (after One-Hot Encoding)

For multi-select columns, each option will be converted into a binary variable (e.g., 1 if selected, 0 if not). Then, Chi-square tests can be performed for each new binary variable against other categorical variables.

1.  **`Which of the following do you think counts as e-waste?`**
    *   *Example Hypothesis (for each option):*
        *   **H0:** There is no association between believing 'Mobile Phones' count as e-waste and having heard the term “E-waste”.
        *   **H1:** There is an association between believing 'Mobile Phones' count as e-waste and having heard the term “E-waste”.

2.  **`Would you be more likely to recycle e-waste if:`**
    *   *Example Hypothesis (for each option):*
        *   **H0:** There is no association between knowing of safe disposal services and being more likely to recycle e-waste if 'Convenient drop-off points were available'.
        *   **H1:** There is an association between knowing of safe disposal services and being more likely to recycle e-waste if 'Convenient drop-off points were available'.

## Prepare Data for Chi-square Tests

### Subtask:
Select appropriate pairs of categorical variables from the dataset that align with the formulated hypotheses. Ensure data is in a suitable format for Chi-square analysis, especially by handling multi-select columns.
"""

df_chi_square = df.copy()
print("Created df_chi_square, a copy of the original DataFrame.")

def process_multi_select(df, column_name):    # Get all unique options by splitting the strings and flattening the list
    all_options = df[column_name].apply(lambda x: str(x).split(';')).explode().unique()

    # Handle cases like 'I don't know' or 'None of the above' if they are meant to be excluded
    # For now, let's assume all listed options are valid categories.

    # Create new binary columns for each option
    for option in all_options:
        # Clean up option names for column headers
        cleaned_option = option.replace(' ', '_').replace('/', '_').replace('(', '').replace(')', '').replace('.', '').replace(',', '').replace('-', '_').replace('?', '').strip().lower()
        new_col_prefix = column_name.split('\n')[0].strip().replace(' ', '_').replace('/', '_').replace('?', '')
        new_col_name = f"{new_col_prefix}_{cleaned_option}"
        df[new_col_name] = df[column_name].apply(lambda x: 1 if option in str(x).split(';') else 0)
    return df

# Process the first multi-select column
df_chi_square = process_multi_select(df_chi_square, 'Which of the following do you think counts as e-waste?\n(Select all that apply.)')

print("Processed 'Which of the following do you think counts as e-waste?' multi-select column. Displaying new columns:")
# Display the head of the DataFrame with new columns to verify. Adjusting filter based on actual column naming.
new_col_prefix = 'Which_of_the_following_do_you_think_counts_as_e-waste_'
print(df_chi_square.filter(like=new_col_prefix).head())



def process_multi_select(df, column_name):
    # Get all unique options by splitting the strings and flattening the list
    all_options = df[column_name].apply(lambda x: str(x).split(';')).explode().unique()

    # Create new binary columns for each option
    for option in all_options:
        # Clean up option names for column headers
        cleaned_option = option.replace(' ', '_').replace('/', '_').replace('(', '').replace(')', '').replace('.', '').replace(',', '').replace('-', '_').replace('?', '').strip().lower()
        # Ensure the prefix also handles special characters like ':'
        new_col_prefix = column_name.split('\n')[0].strip().replace(' ', '_').replace('/', '_').replace('?', '').replace(':', '')
        new_col_name = f"{new_col_prefix}_{cleaned_option}"
        df[new_col_name] = df[column_name].apply(lambda x: 1 if option in str(x).split(';') else 0)
    return df

# Re-process the second multi-select column with the corrected function
df_chi_square = process_multi_select(df_chi_square, 'Would you be more likely to recycle e-waste if:\n(Select up to TWO)')

print("Processed 'Would you be more likely to recycle e-waste if:' multi-select column. Displaying new columns:")
# Adjusting filter based on the corrected column naming convention.
new_col_prefix_2_corrected = 'Would_you_be_more_likely_to_recycle_e-waste_if_'
print(df_chi_square.filter(like=new_col_prefix_2_corrected).head())

chi_square_pairs = [
    ('Have you heard the term “E-waste” before?', 'What did you do with the last electronic device you stopped using?'),
    ('Have you heard the term “E-waste” before?', 'Do you know of any place or service where you can safely dispose of e-waste?'),
    ('Do you currently have unused or broken electronic items at home?', 'Do you know of any place or service where you can safely dispose of e-waste?'),
    ('Why did you choose that option?\n(Choose ONE most important reason)', 'What do you think happens to e-waste after it is collected?'),
    ('Have you ever seen or interacted with an awareness company related to e-waste?', 'Have you heard the term “E-waste” before?')
]

# Add pairs for multi-select columns based on hypotheses
# Hypothesis 1: Which of the following do you think counts as e-waste? vs. Have you heard the term “E-waste” before?
multi_select_ewaste_cols = [col for col in df_chi_square.columns if col.startswith('Which_of_the_following_do_you_think_counts_as_e-waste_')]
for col in multi_select_ewaste_cols:
    if "i_don't_know" not in col: # Exclude 'i don't know' as it's not an e-waste item
        chi_square_pairs.append((col, 'Have you heard the term “E-waste” before?'))

# Hypothesis 2: Would you be more likely to recycle e-waste if: vs. Do you know of any place or service where you can safely dispose of e-waste?
multi_select_recycle_cols = [col for col in df_chi_square.columns if col.startswith('Would_you_be_more_likely_to_recycle_e-waste_if_')]
for col in multi_select_recycle_cols:
    if 'i_probably_wouldn’t_recycle_anyway' not in col: # Exclude this option as it's a negative indicator
        chi_square_pairs.append((col, 'Do you know of any place or service where you can safely dispose of e-waste?'))


print(f"Defined {len(chi_square_pairs)} pairs for Chi-square tests.")

"""## Perform Chi-square Tests and Visualize Results

### Subtask:
Conduct Chi-square tests on the selected categorical variable pairs to determine significant associations. For significant findings, create appropriate visualizations such as bar diagrams or stacked bar charts to illustrate these relationships.

"""

from scipy.stats import chi2_contingency
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

print("Libraries imported successfully.")

chi_square_results = []
significance_level = 0.05

for col1, col2 in chi_square_pairs:
    print(f"\n--- Testing association between '{col1}' and '{col2}' ---")

    # Create contingency table
    contingency_table = pd.crosstab(df_chi_square[col1], df_chi_square[col2])

    # Perform Chi-square test
    chi2, p_value, dof, expected = chi2_contingency(contingency_table)

    print(f"Chi-square statistic: {chi2:.4f}")
    print(f"P-value: {p_value:.4f}")
    print(f"Degrees of freedom: {dof}")

    # Store results
    chi_square_results.append({
        'column1': col1,
        'column2': col2,
        'chi2_statistic': chi2,
        'p_value': p_value,
        'dof': dof
    })

    # Visualize if significant
    if p_value < significance_level:
        print("Significant association found. Generating plot...")
        plt.figure(figsize=(12, 7))

        # Check if the second column is binary (0 or 1) for countplot vs stacked bar
        if set(df_chi_square[col2].unique()).issubset({0, 1}):
            # For binary second column, a grouped bar chart might be more informative
            # Or, if we want to show proportion, a stacked bar chart of normalized values
            # Let's try a stacked bar chart by default if crosstab makes sense

            # Normalize to show proportions for stacked bar chart
            normalized_table = contingency_table.div(contingency_table.sum(1).astype(float), axis=0)
            normalized_table.plot(kind='bar', stacked=True, figsize=(12, 7))
            plt.title(f'Association between {col1} and {col2} (P-value: {p_value:.3f})')
            plt.xlabel(col1)
            plt.ylabel(f'Proportion of {col2}')
            plt.xticks(rotation=45, ha='right')
            plt.legend(title=col2)
            plt.tight_layout()
            plt.show()
        else:
            # For general categorical variables, a stacked bar chart is good
            contingency_table.plot(kind='bar', stacked=True, figsize=(12, 7))
            plt.title(f'Association between {col1} and {col2} (P-value: {p_value:.3f})')
            plt.xlabel(col1)
            plt.ylabel('Count')
            plt.xticks(rotation=45, ha='right')
            plt.legend(title=col2)
            plt.tight_layout()
            plt.show()
    else:
        print("No significant association found (P-value >= 0.05).")

print("\n--- All Chi-square Test Results ---")
for result in chi_square_results:
    print(f"Column 1: {result['column1']}, Column 2: {result['column2']}, Chi2: {result['chi2_statistic']:.4f}, P-value: {result['p_value']:.4f}")

"""## Prepare Data for T-tests

### Subtask:
Prepare the data for T-tests by converting the ordinal column `'Do you currently have unused or broken electronic items at home?'` into a numerical representation and creating a binary variable from `'Have you heard the term “E-waste” before?'` for comparison. This will allow for the evaluation of the hypothesis regarding e-waste awareness and the quantity of e-waste at home.
"""

df_ttest = df_chi_square.copy()

# Convert ordinal column to numerical
ordinal_mapping = {
    'No': 0,
    'Yes, 1-2 items': 1,
    'Yes, many': 2
}
df_ttest['e_waste_at_home_numeric'] = df_ttest['Do you currently have unused or broken electronic items at home?'].map(ordinal_mapping)

# Convert binary categorical column to numerical
binary_mapping = {
    'Yes': 1,
    'No': 0,
    'Not sure': 0 # Group 'Not sure' with 'No' for binary comparison
}
df_ttest['heard_e_waste_binary'] = df_ttest['Have you heard the term “E-waste” before?'].map(binary_mapping)

print("Created 'e_waste_at_home_numeric' and 'heard_e_waste_binary' columns for T-test.")
print("Displaying head of transformed columns:")
print(df_ttest[['e_waste_at_home_numeric', 'heard_e_waste_binary']].head())

from scipy import stats

# Separate data into two groups based on 'heard_e_waste_binary'
group_yes = df_ttest[df_ttest['heard_e_waste_binary'] == 1]['e_waste_at_home_numeric']
group_no = df_ttest[df_ttest['heard_e_waste_binary'] == 0]['e_waste_at_home_numeric']

# Perform independent samples t-test
t_statistic, p_value_ttest = stats.ttest_ind(group_yes, group_no, equal_var=False) # Assuming unequal variances

print(f"\n--- T-test Results for E-waste Awareness vs. E-waste at Home ---")
print(f"Mean for 'Heard E-waste' (Yes): {group_yes.mean():.2f}")
print(f"Mean for 'Heard E-waste' (No/Not sure): {group_no.mean():.2f}")
print(f"T-statistic: {t_statistic:.4f}")
print(f"P-value: {p_value_ttest:.4f}")

significance_level = 0.05
if p_value_ttest < significance_level:
    print("Significant difference found. Generating plot...")
    plt.figure(figsize=(8, 6))
    sns.boxplot(x='heard_e_waste_binary', y='e_waste_at_home_numeric', data=df_ttest)
    plt.xlabel('Heard E-waste Term (0: No/Not sure, 1: Yes)')
    plt.ylabel('Quantity of E-waste at Home (0: No, 1: 1-2 items, 2: Many)')
    plt.title(f'E-waste Quantity at Home by Awareness (P-value: {p_value_ttest:.3f})')
    plt.xticks([0, 1], ['No/Not sure', 'Yes'])
    plt.tight_layout()
    plt.show()
else:
    print("No significant difference found (P-value >= 0.05).")

"""## Generate Overall Distribution Plots for Key Categorical Variables

### Subtask:
Generate bar diagrams for the overall distribution of key categorical variables to provide a general understanding of participant responses. This helps in grasping the baseline awareness and behaviors related to e-waste in the dataset.
"""

key_categorical_cols = [
    'Have you heard the term “E-waste” before?',
    'What did you do with the last electronic device you stopped using?',
    'Do you currently have unused or broken electronic items at home?',
    'What do you think happens to e-waste after it is collected?',
    'Do you know of any place or service where you can safely dispose of e-waste?',
    'Have you ever seen or interacted with an awareness company related to e-waste?'
]

print("Generating overall distribution plots for key categorical variables:")

for col in key_categorical_cols:
    plt.figure(figsize=(10, 6))
    sns.countplot(y=df[col], order=df[col].value_counts().index, palette='viridis')
    plt.title(f'Distribution of {col}')
    plt.xlabel('Count')
    plt.ylabel(col)
    plt.tight_layout()
    plt.show()

print("Overall distribution plots generated.")

"""## Generate Contingency Table Heatmaps

### Subtask:
For some key categorical variable pairs, create heatmaps of their contingency tables. This will provide a different visual representation of the associations (or lack thereof) compared to stacked bar charts, by showing the density of observations across categories.

"""

print("Generating contingency table heatmaps for significant associations...")

for result in chi_square_results:
    col1 = result['column1']
    col2 = result['column2']
    p_value = result['p_value']

    if p_value < significance_level:
        print(f"\n--- Creating heatmap for '{col1}' and '{col2}' (P-value: {p_value:.4f}) ---")

        # Create contingency table
        contingency_table = pd.crosstab(df_chi_square[col1], df_chi_square[col2])

        # Create heatmap
        plt.figure(figsize=(10, 8))
        sns.heatmap(contingency_table, annot=True, fmt="d", cmap="viridis", linewidths=.5)
        plt.title(f'Contingency Table Heatmap: {col1} vs. {col2}\nP-value: {p_value:.4f}')
        plt.xlabel(col2)
        plt.ylabel(col1)
        plt.tight_layout()
        plt.show()
    else:
        print(f"No significant association found for '{col1}' and '{col2}' (P-value: {p_value:.4f}). Skipping heatmap.")

print("Heatmaps generation complete.")

"""**Reasoning**:
The previous step successfully generated heatmaps for significant categorical variable pairs. The next part of the main task is to generate bar charts for the distributions of individual options within multi-select columns. I will iterate through the columns created from the multi-select questions and plot their distributions.


"""



"""**Reasoning**:
The previous code generated a `FutureWarning` from Seaborn regarding the use of `palette` without `hue`. To address this, I will update the `sns.barplot` calls to explicitly set `hue=counts.index` and `legend=False` as suggested by the warning, which will align with future Seaborn versions and eliminate the warning.


"""

print("Generating bar charts for individual options within multi-select columns...")

# List of prefixes for the one-hot encoded multi-select columns
multi_select_prefixes = [
    'Which_of_the_following_do_you_think_counts_as_e-waste_',
    'Would_you_be_more_likely_to_recycle_e-waste_if_'
]

for prefix in multi_select_prefixes:
    # Get all columns that match the current prefix
    option_cols = [col for col in df_chi_square.columns if col.startswith(prefix)]

    if not option_cols:
        print(f"No columns found for prefix: {prefix}")
        continue

    # Prepare data for plotting: sum of '1's for each option
    # Transpose to have options as rows and '1's as the single column of counts
    counts = df_chi_square[option_cols].sum().sort_values(ascending=False)

    plt.figure(figsize=(12, 7))
    sns.barplot(x=counts.values, y=counts.index, palette='viridis', hue=counts.index, legend=False)

    # Clean up column names for better readability on the plot
    cleaned_labels = [label.replace(prefix, '').replace('_', ' ').title() for label in counts.index]
    plt.yticks(ticks=range(len(cleaned_labels)), labels=cleaned_labels)

    plt.title(f'Distribution of Options for: {prefix.replace('_', ' ').replace('e-waste?', 'e-waste').strip().title()}')
    plt.xlabel('Number of Selections')
    plt.ylabel('Option')
    plt.tight_layout()
    plt.show()

print("Bar charts for multi-select options generated.")

"""## Summary:

### Q&A
The process successfully generated contingency table heatmaps for significant categorical variable pairs. Heatmaps were created for three pairs demonstrating a significant association (p-value < 0.05) with the question "Have you heard the term `E-waste` before?". Bar charts were also successfully generated to visualize the distribution of individual options within two multi-select columns, providing insights into perceptions of e-waste components and factors influencing recycling behavior.

### Data Analysis Key Findings
*   **Significant Associations with E-waste Awareness**: Three specific pairs of categorical variables showed statistically significant associations (p-value < 0.05) with the question "Have you heard the term `E-waste` before?":
    *   'Which_of_the_following_do_you_think_counts_as_e-waste_mobile_phones' (p-value: 0.0106)
    *   'Which_of_the_following_do_you_think_counts_as_e-waste_laptops_computers' (p-value: 0.0111)
    *   'Which_of_the_following_do_you_think_counts_as_e-waste_chargers_earphones' (p-value: 0.0049)
    These associations were visualized using contingency table heatmaps, illustrating the density of observations across categories for these significant relationships.
*   **Multi-Select Option Distributions**: Bar charts were generated for the individual options within multi-select questions, such as "Which of the following do you think counts as e-waste?" and "Would you be more likely to recycle e-waste if?". These charts displayed the frequency of selection for each option, providing a clear view of how respondents perceive e-waste components and what factors might encourage them to recycle.

### Insights or Next Steps
*   The significant associations between general e-waste awareness and the recognition of specific items (mobile phones, laptops/computers, chargers/earphones) as e-waste suggest that targeted educational efforts focusing on common household electronics could effectively improve public understanding of e-waste.
*   Analyzing the distributions of multi-select options can reveal the most prevalent misconceptions about what constitutes e-waste or identify the most compelling incentives for recycling. This information is crucial for designing effective public awareness campaigns and developing actionable recycling policies.

## Summary:

### Q&A
This analysis aimed to understand the relationships between different factors concerning e-waste awareness and behavior. The specific questions addressed through statistical tests and visualizations include:
*   Does basic awareness of the term "E-waste" translate into specific disposal actions or knowledge of safe disposal services?
*   Is the presence of e-waste at home related to knowledge of disposal services?
*   Do reasons for disposal or perception of e-waste's fate correlate with other awareness factors?
*   Does knowing the term "E-waste" influence the correct identification of common electronic items as e-waste?
*   Is there a difference in the quantity of e-waste accumulated at home between those aware of the term "E-waste" and those who are not?
*   What are the prevailing disposal behaviors, the extent of e-waste accumulation, and the public's knowledge of disposal services and awareness campaigns?

### Data Analysis Key Findings
*   **Awareness of E-waste Term vs. E-waste Identification:** A significant association (p-values < 0.05) was found between having heard the term "E-waste" and correctly identifying mobile phones (p=0.0106), laptops/computers (p=0.0111), and chargers/earphones (p=0.0049) as e-waste.
*   **Limited Impact of Term Awareness on Behavior/Knowledge:** There was no significant association (p-values \>= 0.05) between hearing the term "E-waste" and actual disposal behavior (p=0.1520), knowledge of disposal services (p=0.1075), or the quantity of e-waste accumulated at home (p=0.8956, mean of 1.10 items for aware vs. 1.08 for unaware).
*   **General Awareness is High, but Practical Knowledge is Low:** Approximately 84% of respondents had heard the term "E-waste," but a majority (around 60%) did not know of any safe e-waste disposal services.
*   **Prevalence of E-waste Accumulation and Informal Disposal:** Around 83% of respondents reported having unused or broken electronic items at home. The most common disposal method for the last device was 'Kept it at home' (around 50%), followed by 'Gave it to a family member' (around 20%). Formal recycling was less common.
*   **Limited Reach of Awareness Campaigns:** Around 70% of respondents had not interacted with an e-waste awareness company.
*   **No Link Between Disposal Factors and Knowledge of Services:** Factors like 'Free door-to-door pickup', 'Data destruction guaranteed', or 'Small incentive provided' were not significantly associated with pre-existing knowledge of disposal services (p-values \>= 0.0846).

### Insights or Next Steps
*   Educational initiatives should focus on bridging the gap between basic e-waste term awareness and practical knowledge, emphasizing what specific items constitute e-waste and the importance of formal recycling channels.
*   Efforts are needed to make information about safe e-waste disposal services more accessible and prominent, coupled with broader and more impactful awareness campaigns that address convenience, data security, and clear process explanations to motivate responsible disposal.
"""